"""changes in ascent data to allow scraped data load

Revision ID: d7b266e64c93
Revises: e6a05d7a4a93
Create Date: 2026-01-18 15:19:51.985279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b266e64c93'
down_revision: Union[str, Sequence[str], None] = 'e6a05d7a4a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_climbed_problems', sa.Column('date_climbed', sa.DateTime(), nullable=True))
    op.add_column('user_responses', sa.Column('nationality', sa.String(), nullable=True))
    # Manually add the nullable change
    op.alter_column('user_responses', 'browser_id',
                    existing_type=sa.String(), 
                    index = False,
                    nullable=True) 
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'nationality')
    op.drop_column('user_climbed_problems', 'date_climbed')

    # Revert nullable change
    op.alter_column('user_responses', 'browser_id',
                    existing_type=sa.String(),
                    index = True,
                    nullable=False)
    # ### end Alembic commands ###
