"""removed param to test

Revision ID: d7fe0467f0f8
Revises: d1999a9d2cc2
Create Date: 2026-01-16 13:47:20.619765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fe0467f0f8'
down_revision: Union[str, Sequence[str], None] = 'd1999a9d2cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'bleau_info_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('bleau_info_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
