"""added param again to test

Revision ID: e6a05d7a4a93
Revises: d7fe0467f0f8
Create Date: 2026-01-16 13:48:25.088808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a05d7a4a93'
down_revision: Union[str, Sequence[str], None] = 'd7fe0467f0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_responses', sa.Column('bleau_info_user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_responses', 'bleau_info_user')
    # ### end Alembic commands ###
